name: "S3 Sync - AWS educate"
description: "Sync a directory to an AWS S3 repository with an AWS educate account"
author: jakejarvis, frittatelle
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
